apiVersion: v1
kind: ServiceAccount
metadata:
  name: vytalwatch-api
  namespace: vytalwatch-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vytalwatch-api-role
  namespace: vytalwatch-prod
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vytalwatch-api-rolebinding
  namespace: vytalwatch-prod
subjects:
  - kind: ServiceAccount
    name: vytalwatch-api
    namespace: vytalwatch-prod
roleRef:
  kind: Role
  name: vytalwatch-api-role
  apiGroup: rbac.authorization.k8s.io
